- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "hello {{course | default('Ansible')}}"

- name: lowercase
  hosts: localhost
  vars:
    Greetings: good morning
  tasks:
  - name: convert to lowercase
    ansible.builtin.debug:
      msg: "hello {{Greetings | lower}}"

- name: upperrcase
  hosts: localhost
  vars:
    Greetings: good morning
  tasks:
  - name: convert to uppercase
    ansible.builtin.debug:
      msg: "hello {{Greetings | upper}}"

- name: min and max ages
  hosts: localhost
  vars:
    ages: [12,45,66,7]
  tasks:
  - name: min ages
    ansible.builtin.debug:
      msg: "minimum age is {{ages | min }}"

- name: min and max ages
  hosts: localhost
  vars:
    ages: [12,45,66,7]
  tasks:
  - name: max ages
    ansible.builtin.debug:
      msg: "minimum age is {{ages | max }}"

  



