- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "hello {{course | default('Ansible')}}"

- name: lowercase
  hosts: localhost
  vars:
    Greetings: good morning
  tasks:
  - name: convert to lowercase
    ansible.builtin.debug:
      msg: "hello {{Greetings | lower}}"

- name: upperrcase
  hosts: localhost
  vars:
    Greetings: good morning
  tasks:
  - name: convert to uppercase
    ansible.builtin.debug:
      msg: "hello {{Greetings | upper}}"

- name: min and max ages
  hosts: localhost
  vars:
    ages: [12,45,66,7]
  tasks:
  - name: min ages
    ansible.builtin.debug:
      msg: "minimum age is {{ages | min }}"

- name: min and max ages
  hosts: localhost
  vars:
    ages: [12,45,66,7]
  tasks:
  - name: max ages
    ansible.builtin.debug:
      msg: "maximum age is {{ages | max }}"


- name: convert dic to item
  hosts: localhost
  vars:
    my_dic:
      course: ansible
      Trainer: Pushpa
      Duration: 6 months
  tasks:
  - name: before convertion
    ansible.builtin.debug:
      msg: "before convertion: {{my_dic}}"

  - name: after convertion
    ansible.builtin.debug:
      msg: "after convertion: {{my_dic | dict2items}}"


- name: convert items into dictionary
  hosts: localhost
  vars:
    my_items:
      - {'key' : 'course' , 'value' : 'ansible'}
      - {'key' : 'trainer' , 'value' : 'pushpa'}
      - {'key' : 'duration' , 'value' : '6 months'}
  tasks:
  - name: before convertion
    ansible.builtin.debug:
      msg: "before convertion: {{my_items}}"

  - name: after convertion
    ansible.builtin.debug:
      msg: "after convertion: {{my_items | items2dict}}"

  



